export const DATABASE_CONSTANTS = {
  DEFAULT_PAGE_SIZE: 10,
  MAX_PAGE_SIZE: 100,
  PASSWORD_SALT_ROUNDS: 12,
  DEFAULT_TIMEZONE: '+03:00',
  CONNECTION_TIMEOUT: 30000,
  ACQUIRE_TIMEOUT: 60000,
  TIMEOUT: 60000,
} as const;

export const PAGINATION_CONSTANTS = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: DATABASE_CONSTANTS.DEFAULT_PAGE_SIZE,
  MAX_LIMIT: DATABASE_CONSTANTS.MAX_PAGE_SIZE,
} as const; 